### ISSUE TITLE
Does not work with Contao 4.4.7

### ISSUE THREAD

**Issue by LDI-DAN** [srhinow/meta-4-coremodules#1]
Very good and necessary module but unfortunately does not work in Contao 4.4.7 when installed in Contao Manager gives out error 
Please tell me how you can modify it for Contao 4.4.7
Thank you in advance for your cooperation!

Using version ^0.2.2 for srhinow/meta-4-coremodules
/var/www/razmery1/data/www/1s-uslugi.ru/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for contao/managed-edition No version set (parsed as 1.0.0) -> satisfiable by contao/managed-edition[No version set (parsed as 1.0.0)].
    - srhinow/meta-4-coremodules 0.2.2 requires contao/core-bundle ~3.5, < 4.0-dev -> satisfiable by contao/core[3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.28, 3.5.29, 3.5.3, 3.5.30, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - contao/core 3.5.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.10 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.11 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.12 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.13 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.14 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.15 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.16 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.17 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.18 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.19 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.20 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.21 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.22 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.23 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.24 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.25 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.26 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.27 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.28 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.29 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.30 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.6 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.7 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.8 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.9 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - Installation request for srhinow/meta-4-coremodules ^0.2.2 -> satisfiable by srhinow/meta-4-coremodules[0.2.2].

Installation failed, reverting /var/www/razmery1/data/www/1s-uslugi.ru/composer.json to its original content.
--------------------------------------------------------
Exception occured: Error: command exit code was 2
#0 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/razmer...')
#3 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/razmer...')
#4 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: Error: command exit code was 2
#0 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/razmer...')
#3 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/razmer...')
#4 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/razmery1/data/www/1s-uslugi.ru/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
--------------------------------------------------------

Process terminated with exit code 1
Reason: General error

**Comment by srhinow** [comment]
thanks LDI-DAN 
yes version 0.2.2 is only for 3.5 and < 4. try now current version 0.2.5 this is also for contao 4.4. testet in 4.4.8 me.
change in #ebd71a7
