### ISSUE TITLE
Meta-Description-Feld auf 320 Zeichen erweitern.

### ISSUE THREAD

**Issue by netgroup-gmbh** [srhinow/meta-4-coremodules#3]
Hallöchen,
Google hat seine Zeichenanzahl für die Meta-Description erhöht. Kannst Du bitte auch das Feld dementsprechend erweitern?
Vielen Dank!
Adelaide

**Comment by srhinow** [comment]
Hallo Adelaide,
hab ich jetzt in 0.2.6 auf 325 Zeichen angepasst. 

Gruß Sven

**Comment by seibtph** [comment]
Das habe ich gerade getestet, aber es ist immer noch eine maxlength von 180 Zeichen bei dem Eingabefeld für die Beschreibung gesetzt.

**Comment by srhinow** [comment]
ja hatte die DB-Felder zwar angepasst aber die dca-maxlength nicht. Hab ich jetzt in der 0.2.6.1 gefixt

**Comment by seibtph** [comment]
Danke. Es lässt sich aber noch nicht auf diese Version updaten. Bei Packagist ist immer noch die 0.2.6 die aktuellste?

**Comment by srhinow** [comment]
habs jetzt auch bei packagist aktualisert
